Repository sdss/marvin, pull requests merged in 2018-08, with the labels that each got.

#512 Fixes bug in map plotting using sky coordinates
  CHANGELOG.rst
  python/marvin/tests/utils/plot/test_map.py
  python/marvin/utils/plot/map.py
Labels: bug, plotting, priority-high

#506 New Marvin Image Tool
  CHANGELOG.rst
  docs/sphinx/api/mixins.rst
  docs/sphinx/api/tools.rst
  docs/sphinx/api/utils.rst
  docs/sphinx/core.rst
  docs/sphinx/index.rst
  docs/sphinx/tools.rst
  docs/sphinx/tools/image.rst
  docs/sphinx/utils/images.rst
  docs/sphinx/whats-new.rst
  python/marvin/core/exceptions.py
  python/marvin/db/DatabaseConnection.py
  python/marvin/extern/yanny.py
  python/marvin/tests/test_imports.py
  python/marvin/tests/tools/test_image.py
  python/marvin/tools/__init__.py
  python/marvin/tools/core.py
  python/marvin/tools/image.py
  python/marvin/tools/image/__init__.py
  python/marvin/tools/image/image.py
  python/marvin/tools/mixins/__init__.py
  python/marvin/tools/mixins/mma.py
  python/marvin/utils/general/__init__.py
  python/marvin/utils/general/bundle.py
  python/marvin/utils/general/general.py
  python/marvin/utils/general/images.py
Labels: enhancement

#488 ivar propagation for np.log10(Map)
  CHANGELOG.rst
  python/marvin/tests/tools/test_map.py
  python/marvin/tools/quantities/map.py
Labels: bug, marvin-tools, priority-developers, priority-high, priority-science
