Repository sdss/marvin, pull requests merged in 2018-07, with the labels that each got.

#481 Hides map plotting function `ax_setup()`
  CHANGELOG.rst
  docs/sphinx/utils/plot-map.rst
  python/marvin/tests/utils/plot/test_map.py
  python/marvin/utils/plot/map.py
Labels: documentation, enhancement, priority-low

#483 raises error when applying stellar sigma correction in MPL-6
  CHANGELOG.rst
  docs/sphinx/known-issues.rst
  docs/sphinx/web.rst
  docs/sphinx/whats-new.rst
  python/marvin/core/exceptions.py
  python/marvin/db/models/DapModelClasses.py
  python/marvin/tests/tools/test_map.py
  python/marvin/tests/web/test_galaxy.py
  python/marvin/tools/maps.py
  python/marvin/tools/quantities/map.py
  python/marvin/utils/general/general.py
  python/marvin/web/controllers/galaxy.py
Labels: enhancement

#487 Fix for bug when explicitly returning default parameters in query
  CHANGELOG.rst
  python/marvin/db/models/DapModelClasses.py
  python/marvin/tests/conftest.py
  python/marvin/tests/tools/test_query.py
  python/marvin/tools/query.py
  python/marvin/tools/results.py
  python/marvin/utils/datamodel/query/MPL.py
Labels: bug
